### ISSUE TITLE
[k8s] 용어 정리

### ISSUE THREAD

**Issue by daehwan2da** [daehwan2da/study#5]
#### StatefulSet ([link](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/))
StatefulSet 은 workload API object 로, Stateful 한 Application 을 관리하기 위함이다.
- 생성되는 Pod 명의 접미사는 숫자 인덱스가 부여된다.
  - sample-statefulset-0, sample-statefulset-1, ...
  - Pod 명이 변경되지 않는다.
- 데이터를 영구적으로 저장힉 위한 구조로 되어있다.
- valuable for applications
  - 안정적이고, 유니크한 네트워크 구분자가 필요한 경우
  - 안정적이고, 영구적인 저장소가 필요한 경우 (상태 유지)
  - graceful 한 deployment, scalling (ordered)
  - 자동적으로 업데이트 (ordered)

``` yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sample-statefulset
spec:
  serviceName: sample-statefulset
  replicas: 3
  selector:
    matchLabels:
      app: sample-app
    template:
      metadata:
        labels:
          app: sample-app
      spec:
        containers:
        - name: nginx-container
          image: nginx:1.16
          volumnMounts:
          - name: www
            mountPath: /usr/share/nginx/html
  volumneChainTemplates:
  - metadata:
      name: www
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1G

```
